'''Utility functions and objects'''

book_name_code_map = {
    "1 Chronicles": "1CH",
    "1 Corinthians": "1CO",
    "1 John": "1JN",
    "1 Kings": "1KI",
    "1 Peter": "1PE",
    "1 Samuel": "1SA",
    "1 Thessalonians": "1TH",
    "1 Timothy": "1TI",
    "2 Chronicles": "2CH",
    "2 Corinthians": "2CO",
    "2 John": "2JN",
    "2 Kings": "2KI",
    "2 Peter": "2PE",
    "2 Samuel": "2SA",
    "2 Thessalonians": "2TH",
    "2 Timothy": "2TI",
    "3 John": "3JN",
    "Acts": "ACT",
    "Amos": "AMO",
    "Colossians": "COL",
    "Daniel": "DAN",
    "Deuteronomy": "DEU",
    "Ecclesiastes": "ECC",
    "Ephesians": "EPH",
    "Esther": "EST",
    "Exodus": "EXO",
    "Ezekiel": "EZK",
    "Ezra": "EZR",
    "Galatians": "GAL",
    "Genesis": "GEN",
    "Habakkuk": "HAB",
    "Haggai": "HAG",
    "Hebrews": "HEB",
    "Hosea": "HOS",
    "Isaiah": "ISA",
    "James": "JAS",
    "Jeremiah": "JER",
    "Job": "JOB",
    "Joel": "JOL",
    "John": "JHN",
    "Jonah": "JON",
    "Joshua": "JOS",
    "Jude": "JUD",
    "Judges": "JDG",
    "Lamentations": "LAM",
    "Leviticus": "LEV",
    "Luke": "LUK",
    "Malachi": "MAL",
    "Mark": "MRK",
    "Matthew": "MAT",
    "Micah": "MIC",
    "Nahum": "NAM",
    "Nehemiah": "NEH",
    "Numbers": "NUM",
    "Obadiah": "OBA",
    "Philemon": "PHM",
    "Philippians": "PHP",
    "Proverbs": "PRO",
    "Psalm": "PSA",
    "Revelation": "REV",
    "Romans": "ROM",
    "Ruth": "RUT",
    "Song of Solomon": "SNG", 	
    "Titus": "TIT",
    "Zechariah": "ZEC",	
    "Zephaniah": "ZEP", 	
}